apiVersion: v1
kind: Service
metadata:
  name: mall-admin
spec:
  type: NodePort
  selector:
    app: mall-admin
  ports:
    - protocol: TCP
      port: 4173
      nodePort: 31230
      name: frontend

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mall-admin
  annotations:
    kubernetes.io/change-cause: registry-vpc.cn-shanghai.aliyuncs.com/shuzhixinghua/mall-admin:{{GIT_COMMIT}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mall-admin
  template:
    metadata:
      labels:
        app: mall-admin
    spec:
      containers:
        - name: mall-admin
          image: registry-vpc.cn-shanghai.aliyuncs.com/shuzhixinghua/mall-admin:{{GIT_COMMIT}}
          ports:
            - containerPort: 4173
          livenessProbe:
            tcpSocket:
              port: 4173
            initialDelaySeconds: 30
            periodSeconds: 600
          readinessProbe:
            tcpSocket:
              port: 4173
            initialDelaySeconds: 5
            periodSeconds: 60
          env:
            - name: NODE_ENV
              value: production
            - name: API_ENV
              value: production
      imagePullSecrets:
        - name: aliyun-registry
